name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-dependencies:
    name: Installing Dependencies
    runs-on: ubuntu-latest
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Setup complete
        run: echo "Dependencies are pre-installed in the container"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Build
        run: make

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Test
        run: make test

  make:
    name: Make
    runs-on: ubuntu-latest
    needs: test
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Make
        run: make
