name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-dependencies:
    name: Installing Dependencies
    runs-on: ubuntu-latest
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup complete
        run: echo "Dependencies are pre-installed in the container"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        id: build-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
      - name: Build
        run: make
      - name: Save build cache
        if: steps.build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ steps.build-cache.outputs.cache-primary-key }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    container: ghcr.io/gravity-sim/deps:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache/restore@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
      - name: Test
        run: make test

  make:
    name: Make
    runs-on: ubuntu-latest
    needs: test
    container: ghcr.io/gravity-sim/deps:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libglew-dev libglfw3-dev 
    - name: Build
      run: make
    - name: Test
      run: make test
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache/restore@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c') }}
      - name: Make
        run: make
