---
name: C/C++ CI

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install-dependencies:
    name: Installing Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: "${{ runner.os }}-build-${{ hashFiles('**/*.c') }}"
          restore-keys: "${{ runner.os }}-build-"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libglew-dev libglfw3-dev libopenmpi-dev

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: "${{ runner.os }}-build-${{ hashFiles('**/*.c') }}"
          restore-keys: "${{ runner.os }}-build-"
      - name: Build
        run: make clean && make

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: "${{ runner.os }}-build-${{ hashFiles('**/*.c') }}"
          restore-keys: "${{ runner.os }}-build-"
      - name: Test
        run: make test

  make:
    name: Make
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            src/*.o
            tests/*.o
          key: "${{ runner.os }}-build-${{ hashFiles('**/*.c') }}"
          restore-keys: "${{ runner.os }}-build-"
      - name: Make
        run: make clean && make
